name: qcmb-training
dependencies:
    - python=3.8.*
    - pip
    - jupyter
    - nbconvert
    - numpy
    - matplotlib
    - pandas
    - seaborn
    - pip:
        - qiskit[visualization] == 0.24.0
