name: qcmb-training
dependencies:
    - python=3.9.*
    - pip
    - jupyter
    - nbconvert
    - numpy
    - matplotlib
    - pandas
    - seaborn
    - pip:
        - qiskit[visualization] == 0.34.2
        - pylatexenc
