name: qcmb-training ci

on:
  push:
  pull_request:
    branches:
      - master

env:
   CONDA_ENV: qcmb-training

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: continuumio/miniconda3
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Install the Environment 
      - name: Install dependencies
        run: |
          conda env create -n $CONDA_ENV -f environment.yml
     
      # Test Files
      - name: "Test Notebooks"
        run: |
          for file in ./content/*.ipynb ./solutions/*.ipynb
          do 
            conda run -n $CONDA_ENV jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --to notebook --execute $file
          done
        env:
          QE_TOKEN: '${{ secrets.QE_TOKEN }}'
          QE_URL: '${{ secrets.QE_URL }}'


